import { IndianRupee, PackageCheck, AlertTriangle, AlertOctagon } from "lucide-react"
import type { InventoryItem, InventoryStatsData } from "./types"

export const inventoryStats: InventoryStatsData[] = [
  {
    title: "Total Inventory Value",
    value: "₹48.6L",
    change: "+12% this quarter",
    changeType: "positive",
    icon: IndianRupee,
  },
  {
    title: "Healthy Stock",
    value: "76 products",
    change: "Stable inventory",
    changeType: "positive",
    icon: PackageCheck,
  },
  {
    title: "Low Stock Alerts",
    value: "8 products",
    change: "Need attention",
    changeType: "neutral",
    icon: AlertTriangle,
  },
  {
    title: "Critical Items",
    value: "3 products",
    change: "Immediate action required",
    changeType: "negative",
    icon: AlertOctagon,
  },
]

export const inventoryItems: InventoryItem[] = [
  {
    id: "INV-001",
    productName: "Wireless Mouse",
    productImage: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=200&h=200&fit=crop",
    sku: "WM-PRO-01",
    category: "Electronics",
    currentStock: 5,
    minimumStock: 50,
    averageDailySales: 12,
    daysUntilStockout: 4,
    supplierName: "TechGear Suppliers Ltd.",
    supplierLeadTime: 7,
    lastRestockDate: "01 May 2026",
    inventoryValue: 4995,
    monthlyDemandGrowth: 15,
    riskLevel: "Critical",
    aiRecommendation: "Purchase 200 units immediately",
  },
  {
    id: "INV-002",
    productName: "Mechanical Keyboard",
    productImage: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=200&h=200&fit=crop",
    sku: "MK-RGB-87",
    category: "Electronics",
    currentStock: 85,
    minimumStock: 20,
    averageDailySales: 4,
    daysUntilStockout: 21,
    supplierName: "KeyBoard Co.",
    supplierLeadTime: 10,
    lastRestockDate: "15 May 2026",
    inventoryValue: 212500,
    monthlyDemandGrowth: 35,
    riskLevel: "Healthy",
    aiRecommendation: "Maintain current stock levels",
  },
  {
    id: "INV-003",
    productName: "USB-C Hub",
    productImage: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=200&h=200&fit=crop",
    sku: "HUB-7IN1-C",
    category: "Accessories",
    currentStock: 12,
    minimumStock: 15,
    averageDailySales: 2.5,
    daysUntilStockout: 4, 
    supplierName: "ConnectX Accessories",
    supplierLeadTime: 5,
    lastRestockDate: "10 Jun 2026",
    inventoryValue: 22788,
    monthlyDemandGrowth: 22,
    riskLevel: "Critical",
    aiRecommendation: "Reorder within 2 days",
  },
  {
    id: "INV-004",
    productName: "Laptop Stand",
    productImage: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=200&h=200&fit=crop",
    sku: "LS-ALUM-01",
    category: "Accessories",
    currentStock: 42,
    minimumStock: 10,
    averageDailySales: 1.5,
    daysUntilStockout: 28,
    supplierName: "ErgoTech Solutions",
    supplierLeadTime: 14,
    lastRestockDate: "20 May 2026",
    inventoryValue: 54558,
    monthlyDemandGrowth: 5,
    riskLevel: "Healthy",
    aiRecommendation: "Optimal stock levels",
  },
  {
    id: "INV-005",
    productName: "Monitor Light Bar",
    productImage: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=200&h=200&fit=crop",
    sku: "LB-PRO-LED",
    category: "Accessories",
    currentStock: 18,
    minimumStock: 25,
    averageDailySales: 3,
    daysUntilStockout: 6,
    supplierName: "Lumens Inc.",
    supplierLeadTime: 12,
    lastRestockDate: "05 Jun 2026",
    inventoryValue: 62982,
    monthlyDemandGrowth: 8,
    riskLevel: "Low",
    aiRecommendation: "Prepare next PO soon",
  },
  {
    id: "INV-006",
    productName: "Webcam",
    productImage: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=200&h=200&fit=crop",
    sku: "WC-1080P-HD",
    category: "Electronics",
    currentStock: 150,
    minimumStock: 20,
    averageDailySales: 1,
    daysUntilStockout: 150,
    supplierName: "VisionTech Cameras",
    supplierLeadTime: 21,
    lastRestockDate: "01 Jan 2026",
    inventoryValue: 449850,
    monthlyDemandGrowth: -15,
    riskLevel: "Watch",
    aiRecommendation: "Reduce excess stock. Run promo.",
  },
  {
    id: "INV-007",
    productName: "Noise Cancelling Headphones",
    productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&h=200&fit=crop",
    sku: "HP-ANC-BT",
    category: "Audio",
    currentStock: 35,
    minimumStock: 15,
    averageDailySales: 2,
    daysUntilStockout: 17,
    supplierName: "Acoustic Audio",
    supplierLeadTime: 10,
    lastRestockDate: "15 May 2026",
    inventoryValue: 174965,
    monthlyDemandGrowth: 12,
    riskLevel: "Healthy",
    aiRecommendation: "Stock is stable",
  },
  {
    id: "INV-008",
    productName: "Bluetooth Speaker",
    productImage: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=200&h=200&fit=crop",
    sku: "BS-WATER-V2",
    category: "Audio",
    currentStock: 22,
    minimumStock: 30,
    averageDailySales: 4,
    daysUntilStockout: 5,
    supplierName: "Acoustic Audio",
    supplierLeadTime: 10,
    lastRestockDate: "01 Jun 2026",
    inventoryValue: 43978,
    monthlyDemandGrowth: 18,
    riskLevel: "Critical",
    aiRecommendation: "Restock urgently. Lead time exceeds stock.",
  },
  {
    id: "INV-009",
    productName: "1TB NVMe SSD",
    productImage: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=200&h=200&fit=crop",
    sku: "SSD-1TB-GEN4",
    category: "Storage",
    currentStock: 48,
    minimumStock: 20,
    averageDailySales: 1.2,
    daysUntilStockout: 40,
    supplierName: "DataDrive Storage",
    supplierLeadTime: 15,
    lastRestockDate: "20 Apr 2026",
    inventoryValue: 431952,
    monthlyDemandGrowth: 2,
    riskLevel: "Healthy",
    aiRecommendation: "Optimal stock levels",
  },
  {
    id: "INV-010",
    productName: "Smart Watch Elite",
    productImage: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=200&h=200&fit=crop",
    sku: "SW-ELITE-BK",
    category: "Wearables",
    currentStock: 28,
    minimumStock: 30,
    averageDailySales: 2.5,
    daysUntilStockout: 11,
    supplierName: "TechGear Suppliers Ltd.",
    supplierLeadTime: 14,
    lastRestockDate: "10 May 2026",
    inventoryValue: 251972,
    monthlyDemandGrowth: 25,
    riskLevel: "Low",
    aiRecommendation: "Prepare PO. Sales increasing.",
  },
]
