import { Users, TrendingUp, Star, AlertTriangle } from "lucide-react"
import type { Customer, CustomerStatsData } from "./types"

export const customerStats: CustomerStatsData[] = [
  {
    title: "Total Customers",
    value: "1,245",
    change: "+9% growth",
    changeType: "positive",
    icon: Users,
  },
  {
    title: "Customer Lifetime Value",
    value: "₹18.5L",
    change: "+14% increase",
    changeType: "positive",
    icon: TrendingUp,
  },
  {
    title: "VIP Customers",
    value: "86",
    change: "High value users",
    changeType: "positive",
    icon: Star,
  },
  {
    title: "Churn Risk",
    value: "34",
    change: "Need attention",
    changeType: "negative",
    icon: AlertTriangle,
  },
]

export const customers: Customer[] = [
  {
    id: "CUS-001",
    name: "Arjun Mehta",
    email: "arjun.m@example.com",
    phone: "+91 98765 43210",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Arjun",
    segment: "VIP",
    totalOrders: 42,
    totalSpent: 1250000,
    averageOrderValue: 29761,
    lastPurchaseDate: "10 Jun 2026",
    joinDate: "15 Jan 2024",
    riskScore: 12,
    aiInsight: "High Lifetime Value",
  },
  {
    id: "CUS-002",
    name: "Neha Sharma",
    email: "neha.s@example.com",
    phone: "+91 87654 32109",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Neha",
    segment: "At Risk",
    totalOrders: 15,
    totalSpent: 85000,
    averageOrderValue: 5666,
    lastPurchaseDate: "02 Feb 2026",
    joinDate: "12 Mar 2025",
    riskScore: 88,
    aiInsight: "Churn Risk",
  },
  {
    id: "CUS-003",
    name: "Rohan Kumar",
    email: "rohan.k@example.com",
    phone: "+91 76543 21098",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Rohan",
    segment: "Loyal",
    totalOrders: 28,
    totalSpent: 340000,
    averageOrderValue: 12142,
    lastPurchaseDate: "05 Jun 2026",
    joinDate: "20 May 2025",
    riskScore: 25,
    aiInsight: "Frequent Buyer",
  },
  {
    id: "CUS-004",
    name: "Priya Desai",
    email: "priya.d@example.com",
    phone: "+91 65432 10987",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Priya",
    segment: "New",
    totalOrders: 2,
    totalSpent: 18500,
    averageOrderValue: 9250,
    lastPurchaseDate: "11 Jun 2026",
    joinDate: "01 Jun 2026",
    riskScore: 40,
    aiInsight: "Growing Customer",
  },
  {
    id: "CUS-005",
    name: "Aditya Singh",
    email: "aditya.s@example.com",
    phone: "+91 54321 09876",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Aditya",
    segment: "VIP",
    totalOrders: 56,
    totalSpent: 2100000,
    averageOrderValue: 37500,
    lastPurchaseDate: "08 Jun 2026",
    joinDate: "10 Feb 2024",
    riskScore: 5,
    aiInsight: "Upsell Opportunity",
  },
  {
    id: "CUS-006",
    name: "Kavya Reddy",
    email: "kavya.r@example.com",
    phone: "+91 99887 76655",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Kavya",
    segment: "Loyal",
    totalOrders: 32,
    totalSpent: 420000,
    averageOrderValue: 13125,
    lastPurchaseDate: "01 Jun 2026",
    joinDate: "05 Aug 2025",
    riskScore: 20,
    aiInsight: "Frequent Buyer",
  },
  {
    id: "CUS-007",
    name: "Vikram Malhotra",
    email: "vikram.m@example.com",
    phone: "+91 88776 65544",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Vikram",
    segment: "At Risk",
    totalOrders: 8,
    totalSpent: 45000,
    averageOrderValue: 5625,
    lastPurchaseDate: "15 Jan 2026",
    joinDate: "22 Sep 2025",
    riskScore: 92,
    aiInsight: "Churn Risk",
  },
  {
    id: "CUS-008",
    name: "Ananya Patel",
    email: "ananya.p@example.com",
    phone: "+91 77665 54433",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Ananya",
    segment: "New",
    totalOrders: 3,
    totalSpent: 24000,
    averageOrderValue: 8000,
    lastPurchaseDate: "12 Jun 2026",
    joinDate: "28 May 2026",
    riskScore: 35,
    aiInsight: "Growing Customer",
  },
  {
    id: "CUS-009",
    name: "Sanjay Gupta",
    email: "sanjay.g@example.com",
    phone: "+91 66554 43322",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Sanjay",
    segment: "VIP",
    totalOrders: 38,
    totalSpent: 1100000,
    averageOrderValue: 28947,
    lastPurchaseDate: "09 Jun 2026",
    joinDate: "30 Apr 2024",
    riskScore: 15,
    aiInsight: "High Lifetime Value",
  },
  {
    id: "CUS-010",
    name: "Meera Nair",
    email: "meera.n@example.com",
    phone: "+91 55443 32211",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Meera",
    segment: "Loyal",
    totalOrders: 25,
    totalSpent: 280000,
    averageOrderValue: 11200,
    lastPurchaseDate: "07 Jun 2026",
    joinDate: "18 Nov 2025",
    riskScore: 28,
    aiInsight: "Upsell Opportunity",
  },
]
